#184651051 make suggested changes on  pre-commit hook (husky)  changes
atlp-rwanda/Team-Sostene-E-commerce-bn pull request #14
Opened 2023-03-19 00:28 UTC by Kress2000

What does this PR do?
Checks code syntax and formats the warnings ad errors after then auto add and commit the changes before pushing

Description of Task to be completed?
installs husky, and initialize eslint
configures again esltrc.json and pre-commit file
More details here on the pictures:
- error example: 
![image](https://user-images.githubusercontent.com/91186046/226146693-152562ef-9d76-4a06-934d-11637c32c21a.png)
- If it is fixable with
```
lint:fix
```
 or
``` 
prettier:fix
```
 commands,  this will be formated automatically by 
```
git commit -m "your message"
```
after staging your work by
```
git add .
```
 _details here on the pictures_
- error solved: 
![image](https://user-images.githubusercontent.com/91186046/226147128-5e25f96d-d1cf-4236-ac9d-cbbb9a9c4769.png)

Any background context you want to provide?
--

[Delivers #184651051]

2023-03-19 06:03 UTC, munezerobagira approved these changes

2023-03-21 16:53 UTC, Kress2000 commented
> check comment

solved

2023-03-21 19:10 UTC, munezerobagira requested changes

2023-03-21 19:10 UTC, munezerobagira commented on src/database/models/usertest.js
>  module.exports = (sequelize, DataTypes) => {
```suggestion
export default (sequelize, DataTypes) => {
```

2023-03-21 19:10 UTC, munezerobagira commented on src/tests/model.test.js
>  });
```suggestion
```

2023-03-21 19:10 UTC, munezerobagira commented on src/tests/model.test.js
>  const sequelize = new Sequelize(config.url);
```suggestion
import Userschema from '../database/models/usertest.ts'
```

2023-03-22 15:52 UTC, munezerobagira requested changes
delete `build` folder and it to the .gitnore

2023-03-22 19:31 UTC, Kress2000 commented
<img width="788" alt="image" src="https://user-images.githubusercontent.com/91186046/227015896-d5c7e298-e620-44c5-aa17-3da3dad4c2b0.png">
By trying to squash the commits: there are left 3 three commits and can't be less unless I reset the changes to develop, otherwise, I am getting conflicts

2023-03-23 10:54 UTC, munezerobagira approved these changes

2023-03-23 10:55 UTC, merged