#184651062 reset password via email
atlp-rwanda/Team-Sostene-E-commerce-bn pull request #20
Opened 2023-03-22 15:00 UTC by mirindi19

##What does this PR do?
 - send an email containing the password reset link
 - reset password

##Description of Task to be completed?
 -Reset password via email

##How should this be manually tested?
 -http://localhost:{PORT}/auth/forgot-password
 -http://localhost:{PORT}/auth/reset-password/{token}

##What are the relevant pivotal tracker/Trello stories?
#184651062

2023-04-04 05:50 UTC, Edcreation requested changes

2023-04-04 05:50 UTC, Edcreation commented on src/middleware/checkUser.js
> +  });
There is a utils file for this

2023-04-04 05:50 UTC, Edcreation commented on src/utils/token.js
> +}
LGTM

2023-04-04 12:56 UTC, AdrineUWERA requested changes

2023-04-04 12:56 UTC, AdrineUWERA commented on src/routes/user.route.js
can you validate the new password the use will be setting.

2023-04-04 15:17 UTC, AdrineUWERA approved these changes

2023-04-05 07:03 UTC, Pacific911 requested changes
check out why the coveralls are failling

2023-04-05 10:07 UTC, AdrineUWERA approved these changes

2023-04-05 10:41 UTC, Edcreation approved these changes

2023-04-05 14:14 UTC, JosephNgabo approved these changes

2023-04-05 14:24 UTC, Pacific911 approved these changes

2023-04-06 15:27 UTC, munezerobagira approved these changes

2023-04-06 15:27 UTC, merged