#184651068  adding product by selle
atlp-rwanda/Team-Sostene-E-commerce-bn pull request #26
Opened 2023-03-28 15:42 UTC by princoo

#### What does this PR do?
- ensure a seller adds the valid product to the products model
- ensure the added product id is also added to the collection model

#### Description of Task to be completed?
- a seller need to be logged in a a seller 
- a seller need to have a collection to add aproduct to
- product body must be valid before its sent 

#### How should this be manually tested?
- using this endpoint `/product/create/${collection id}`

#### What are the relevant pivotal tracker/Trello stories?

#184651068

2023-04-04 05:43 UTC, Edcreation requested changes

2023-04-04 05:43 UTC, Edcreation commented on src/routes/index.js
> +export { productRoute, userRoutes };
Product routes must be also be called here, no need to export them e.g `router.use('/products', productRoutes)`

2023-04-04 05:43 UTC, Edcreation commented on src/index.js
> +sequelize.sync();
we are not using `sequelize.sync()`

2023-04-04 05:43 UTC, Edcreation commented on src/index.js
> +app.use('/product', productRoute);
no need of this it is in `routes/index.js`

2023-04-04 05:43 UTC, Edcreation commented on src/index.js
> +});
No _console.logs_

2023-04-04 05:43 UTC, Edcreation commented on src/services/index.js
> +export { productsServices, userServices, collectionServices };
LGTM

2023-04-05 07:32 UTC, AdrineUWERA requested changes

2023-04-05 07:32 UTC, AdrineUWERA commented on src/database/models/products.model.js
shouldn't the price be a double?

2023-04-05 07:32 UTC, AdrineUWERA commented on src/helpers/cloudinary.js
Is importing dotenv needed in this file?

2023-04-05 07:32 UTC, AdrineUWERA commented on src/helpers/multer.js
You can remove these comments

2023-04-05 07:32 UTC, AdrineUWERA commented on src/routes/product.route.js
> +  checkPermission('SELLER'),
well done

2023-04-05 07:37 UTC, mirindi19 requested changes

2023-04-05 07:37 UTC, mirindi19 commented on src/database/migrations/20230401104008-create-products.js
> +        type: Sequelize.STRING,
Change it to DOUBLE

2023-04-05 07:42 UTC, Edcreation requested changes

2023-04-05 07:42 UTC, Edcreation commented on src/services/products.service.js
> +  });
Its better to pass these items as a single object for code maintainability.

2023-04-05 08:46 UTC, Pacific911 requested changes

2023-04-05 08:46 UTC, Pacific911 commented on src/controllers/user.controller.js
> +          console.log(info);
I think console log is not needed here you remove it !

2023-04-05 09:36 UTC, AdrineUWERA requested changes

2023-04-05 09:36 UTC, AdrineUWERA commented on src/services/products.service.js
You need to make these functions reusable as Eddy suggested in the last change requests. Instead of passing all these params, pass in one object containing everything. U can create this body object in the controllers. That means the createProduct function will receive one parameter (which is the body object), and the addUpdate will receive two parameters (the productId and the body object).

2023-04-05 09:41 UTC, AdrineUWERA commented on src/controllers/product.controller.js
> +  const { productName } = req.body;
You can destructure this in one line

2023-04-05 09:42 UTC, AdrineUWERA commented on src/controllers/product.controller.js
> +  const { productName } = req.body;
I mean all the product details from the body

2023-04-05 10:42 UTC, ishimwe5555 requested changes

2023-04-05 10:42 UTC, ishimwe5555 commented on src/controllers/product.controller.js
> +            console.log(image.url);
You could remove the console logging.

2023-04-05 10:42 UTC, ishimwe5555 commented on src/controllers/product.controller.js
> +  const { bonus } = req.body;
You can restructure all of this too.

2023-04-05 10:42 UTC, ishimwe5555 commented on src/database/models/products.model.js
> +    // unique: true,
unnecessary comment

2023-04-05 10:42 UTC, ishimwe5555 commented on src/database/models/products.model.js
> +  },
As you did Double for the price wouldn't it be the same thing for bonus?

2023-04-05 10:42 UTC, ishimwe5555 commented on src/database/models/products.model.js
> +  },
As you did Double for the price wouldn't it be the same thing for bonus?

2023-04-05 10:42 UTC, ishimwe5555 commented on src/index.js
> +// import router, { userRoutes, productRoute } from './routes';
This is an unnecessary comment too.

2023-04-05 13:50 UTC, AdrineUWERA approved these changes

2023-04-05 14:27 UTC, Pacific911 approved these changes

2023-04-05 14:29 UTC, mirindi19 approved these changes

2023-04-11 08:55 UTC, merged