#184651073 seller updating products from the collection
atlp-rwanda/Team-Sostene-E-commerce-bn pull request #37
Opened 2023-04-13 12:42 UTC by Pacific911

#### What does this PR do?

It will be used to update a specific item in the collection
Such that items always have the right/required status, details and specifications

It consists of the endpoint working well

- PATCH `/product/update/:cid` to update the product item in the collection

#### Description of Task to be completed?

-  A Seller should be able to update the product item from his/her own collection

#### How should this be manually tested?

Use the below endpoint to test the update
- PATCH `/product/update/:cid` to update the product item in the collection

#### What are the relevant pivotal tracker/Trello stories?

- 184651073

2023-04-24 12:23 UTC, Edcreation requested changes

2023-04-24 12:23 UTC, Edcreation commented on src/controllers/product.controller.js
>    const collectionName = req.body.name;
ayncwrapper is being called in routes

2023-04-24 13:05 UTC, Pacific911 commented on src/controllers/product.controller.js
>    const collectionName = req.body.name;
changes requested done 👍

2023-04-24 13:49 UTC, princoo approved these changes

2023-04-25 06:18 UTC, munezerobagira requested changes

2023-04-25 06:18 UTC, munezerobagira commented on src/controllers/updateCollectionItem.controller.js
> +      const Image = await product.getProductImages();
we can use the eager loading to avoid multiple querys

2023-04-25 06:18 UTC, munezerobagira commented on src/controllers/updateCollectionItem.controller.js
> +      }
we can update the the image  id not by index

2023-04-28 10:45 UTC, closed without merging