#184651053 Integrate Coveralls code coverage service
atlp-rwanda/Team-Sostene-E-commerce-bn pull request #4
Opened 2023-03-09 22:20 UTC by AdrineUWERA

### What does this PR do?
Sets up the coverage service in the project

### Description of Task to be completed?
- Adds coveralls to the GitHub repository to get the repo_token
- Adds packages needed for tests and generating coverage report
- Sets the minimum coverage to be 80 percent for lines, branches, and functions

#### How should this be manually tested?
After cloning the repository and installing all required dependencies run command `npm run coverage`

### Any background context you want to provide?
The coverage tools used are mocha, chai, chai-http, and c8 to generate coverage report.

#### What are the relevant pivotal tracker/Trello stories?
#184651053

2023-03-11 15:27 UTC, munezerobagira commented
can you resolve the conflict

2023-03-12 07:41 UTC, munezerobagira requested changes
Add coverage in .gitignore

2023-03-13 04:54 UTC, munezerobagira commented
Good you have included the coverage in `.gitignore`, but you will have to delete coverage directory. It should not be pushed

2023-03-13 07:46 UTC, munezerobagira approved these changes

2023-03-13 08:07 UTC, JosephNgabo approved these changes

2023-03-13 08:10 UTC, Edcreation approved these changes

2023-03-13 08:12 UTC, merged