fix the feature of deleting and updating single item from/in cart
atlp-rwanda/Team-Sostene-E-commerce-bn pull request #64
Opened 2023-06-16 10:36 UTC by Kress2000

#### What does this PR do?
It is a fix to create the feature of deleting and updating a single item from/in the cart

#### Description of Task to be completed?
- ensure that when a user is logged in, and has added some products in cart, he cart edit his products by either deleting single product or update its quantity

#### How should this be manually tested?
swagger documentation in cart tag, you can find all routes

#### What are the relevant pivotal tracker/Trello stories?
none, it is just a fix

#### Screenshots (if appropriate)

https://github.com/atlp-rwanda/Team-Sostene-E-commerce-bn/assets/91186046/a49bd9d3-1814-4edb-b677-6b94b521dd66

2023-06-16 19:00 UTC, AdrineUWERA approved these changes

2023-06-17 19:29 UTC, Edcreation requested changes
Delete this yarn lock. backend is using npm

2023-06-17 19:29 UTC, Edcreation commented on src/services/cart.services.js
> +  console.log(cartWithNoDeletedProd, 'erick');
Remove this console log.

2023-06-17 19:54 UTC, Edcreation approved these changes

2023-06-18 07:45 UTC, munezerobagira approved these changes

2023-06-18 07:45 UTC, merged